# GitHub自動リリースノート生成設定
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: 🔒 Security
      labels:
        - security
    - title: Other Changes
      labels:
        - "*"