# Cross configuration for cross-compilation
# https://github.com/cross-rs/cross

# Linux musl targets
[target.x86_64-unknown-linux-musl]
# Use the latest cross image with pre-installed dependencies
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:latest"

# Linux GNU targets
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

# Environment variables for all targets
[target.env]
# Use vendored libraries to avoid system dependencies
CARGO_NET_GIT_FETCH_WITH_CLI = "true"