# Cross configuration for cross-compilation
# https://github.com/cross-rs/cross

# Build configuration
[build]
# Use vendored dependencies to avoid system library issues
default-target = "x86_64-unknown-linux-gnu"

# Pre-build script to ensure vendored dependencies are used
[build.env]
passthrough = [
    "CARGO_NET_GIT_FETCH_WITH_CLI",
    "RUSTFLAGS",
]

# Linux musl targets - static linking
[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:latest"

# Linux GNU targets
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

# macOS targets don't need cross (native compilation)
[target.x86_64-apple-darwin]
runner = "cargo"

[target.aarch64-apple-darwin]
runner = "cargo"