# cargo-deny configuration file

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause", 
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "0BSD",
    "CC0-1.0",
    "MPL-2.0",
    "Zlib",
]

[bans]
# Lint level for when multiple versions of the same dependency are detected
multiple-versions = "warn"

[advisories]
# Which dependencies to check for advisories
unmaintained = "all"

[sources]
# Lint level for unknown registries
unknown-registry = "warn"
# Lint level for unknown git repos
unknown-git = "warn"